_wandb:
    value:
        cli_version: 0.25.1
        e:
            1psf92cgkmfsci681h2i429cibuz32mz:
                apple: {}
                codePath: FLRegression/main.py
                codePathLocal: main.py
                cpu_count: 10
                cpu_count_logical: 10
                disk:
                    /:
                        total: "994662584320"
                        used: "596515237888"
                email: dinuka.20210433@iit.ac.lk
                executable: /Users/dinukaperera/opt/anaconda3/envs/flower_tutorial/bin/python
                git:
                    commit: 3721e00eb4bcc2900bf4d743d89b03aebb6f7afa
                    remote: git@github.com:J3r3myPerera/FLRegressionFwr.git
                host: Dinukas-MacBook-Pro.local
                memory:
                    total: "17179869184"
                os: macOS-26.3.1-x86_64-i386-64bit
                program: /Users/dinukaperera/FLRegressionFlwr/FLRegression/main.py
                python: CPython 3.10.18
                root: /Users/dinukaperera/FLRegressionFlwr/FLRegression
                startedAt: "2026-03-22T06:54:21.979418Z"
                writerId: 1psf92cgkmfsci681h2i429cibuz32mz
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 2
                - 13
                - 16
                - 61
            "4": 3.10.18
            "5": 0.25.1
            "12": 0.25.1
            "13": darwin-x86_64
adaptive_mu_enabled:
    value: true
description:
    value: SmartFedProx (adaptive μ, hybrid selection)
fraction_fit:
    value: 0.5
local_epochs:
    value: 3
num_clients:
    value: 10
num_rounds:
    value: 30
proximal_mu:
    value: 0.1
selection_strategy:
    value: hybrid
strategy:
    value: SmartFedProx
