"""
Synthetic data generator for indianPersonalFinanceAndSpendingHabits.csv

Core insight from the original dataset:
  - All continuous expense columns are tightly bounded *ratios* of Income
    (e.g. Rent is always 15-30%, Groceries 10-15%, etc.)
  - The original data was generated by sampling ratios first, then multiplying by Income.

Strategy:
  1. For each (Occupation, City_Tier) group, fit a log-normal over Income and a
     multivariate normal over the expense *ratios* (after logit-transforming to
     map the bounded ranges into unrestricted space).
  2. Loan_Repayment is zero-inflated: Bernoulli gate + ratio when non-zero.
  3. Education is exactly 0 when Dependents == 0 (hard rule, preserved).
  4. Derived columns recomputed from their exact formulas:
       Disposable_Income = Income − Σ expenses
       Desired_Savings   = min(Income × pct/100, max(0, Disposable_Income))
       Potential_Savings_* = Uniform(5%,30%) × col  (0%–5% for Healthcare & Education)
"""

import pandas as pd
import numpy as np

SEED = 42
INPUT_PATH = "data/indianPersonalFinanceAndSpendingHabits.csv"
OUTPUT_PATH = "data/indianPersonalFinanceAndSpendingHabits_expanded.csv"
TARGET_ROWS = 100_000

np.random.seed(SEED)

df = pd.read_csv(INPUT_PATH)
original_rows = len(df)
extra_needed = TARGET_ROWS - original_rows
print(f"Original rows: {original_rows}  |  Target: {TARGET_ROWS}  |  Generating: {extra_needed}")

EXPENSE_COLS = [
    "Rent", "Loan_Repayment", "Insurance", "Groceries", "Transport",
    "Eating_Out", "Entertainment", "Utilities", "Healthcare", "Education", "Miscellaneous",
]

# Expense columns that are always positive (model as ratios to Income)
RATIO_COLS = [
    "Rent", "Insurance", "Groceries", "Transport",
    "Eating_Out", "Entertainment", "Utilities", "Healthcare", "Miscellaneous",
]

# Hard bounds on ratios (observed min/max in original data — used for clipping)
RATIO_BOUNDS = {
    "Rent":          (0.15,  0.30),
    "Insurance":     (0.02,  0.05),
    "Groceries":     (0.10,  0.15),
    "Transport":     (0.05,  0.08),
    "Eating_Out":    (0.02,  0.05),
    "Entertainment": (0.02,  0.05),
    "Utilities":     (0.04,  0.08),
    "Healthcare":    (0.03,  0.05),
    "Miscellaneous": (0.01,  0.03),
}

# Loan_Repayment ratio bounds (when non-zero)
LOAN_RATIO_BOUNDS = (0.005, 0.20)
# Education ratio bounds (when Dependents > 0)
EDU_RATIO_BOUNDS  = (0.001, 0.10)

# Desired_Savings_Percentage range
DSP_BOUNDS = (5.0, 24.999)


def logit_transform(x, lo, hi, eps=1e-6):
    """Map x ∈ (lo, hi) → ℝ via logit."""
    p = (x - lo) / (hi - lo)
    p = np.clip(p, eps, 1 - eps)
    return np.log(p / (1 - p))


def sigmoid_inverse(y, lo, hi):
    """Inverse of logit_transform: ℝ → (lo, hi)."""
    p = 1 / (1 + np.exp(-y))
    return lo + p * (hi - lo)


synthetic_parts = []

for (occ, tier), group in df.groupby(["Occupation", "City_Tier"]):
    group = group.reset_index(drop=True)
    n_group = len(group)
    n_new = round(extra_needed * n_group / original_rows)
    if n_new <= 0:
        continue

    # ── Joint model: log(Income) + expense ratios + DSP ─────────────────────
    # Income and DSP are strongly correlated (r≈0.78), so they must be sampled
    # jointly to preserve the tail distribution of Desired_Savings.
    log_income = np.log(group["Income"].values)

    ratio_data = {}
    for col in RATIO_COLS:
        lo, hi = RATIO_BOUNDS[col]
        ratio = (group[col] / group["Income"]).values
        ratio_data[col] = logit_transform(ratio, lo, hi)

    dsp_raw = group["Desired_Savings_Percentage"].values
    dsp_logit = logit_transform(dsp_raw, *DSP_BOUNDS)

    # Stack: [log_income, logit_ratios..., logit_dsp]
    all_joint = np.column_stack([log_income] + list(ratio_data.values()) + [dsp_logit])
    mu_joint = all_joint.mean(axis=0)
    cov_joint = np.cov(all_joint.T) + np.eye(all_joint.shape[1]) * 1e-8

    joint_samples = np.random.multivariate_normal(mu_joint, cov_joint, size=n_new)

    # Back-transform
    income_samples = np.exp(joint_samples[:, 0])

    n_ratio_cols = len(RATIO_COLS)
    ratio_samples = {}
    for i, col in enumerate(RATIO_COLS):
        lo, hi = RATIO_BOUNDS[col]
        ratio_samples[col] = sigmoid_inverse(joint_samples[:, 1 + i], lo, hi)

    dsp_samples = np.clip(
        sigmoid_inverse(joint_samples[:, 1 + n_ratio_cols], *DSP_BOUNDS),
        *DSP_BOUNDS,
    )

    # ── Age: resample + ±2 jitter, clipped to [18, 64] ──────────────────────
    age_new = np.clip(
        np.random.choice(group["Age"].values, n_new, replace=True)
        + np.random.randint(-2, 3, n_new),
        18, 64,
    ).astype(int)

    # ── Dependents: resample from empirical distribution ─────────────────────
    dep_new = np.clip(
        np.random.choice(group["Dependents"].values, n_new, replace=True),
        0, 4,
    ).astype(int)

    # ── Loan_Repayment: Bernoulli + ratio ────────────────────────────────────
    loan_prob = (group["Loan_Repayment"] > 0).mean()
    has_loan = np.random.random(n_new) < loan_prob
    loan_amounts = np.zeros(n_new)
    if has_loan.any():
        pos_ratios = (
            group.loc[group["Loan_Repayment"] > 0, "Loan_Repayment"]
            / group.loc[group["Loan_Repayment"] > 0, "Income"]
        ).values
        lr_logit = logit_transform(pos_ratios, *LOAN_RATIO_BOUNDS)
        lr_mu, lr_std = lr_logit.mean(), lr_logit.std()
        sampled_lr = sigmoid_inverse(
            np.random.normal(lr_mu, lr_std, has_loan.sum()), *LOAN_RATIO_BOUNDS
        )
        loan_amounts[has_loan] = sampled_lr * income_samples[has_loan]

    # ── Education: 0 if Dependents == 0, else sample ratio ──────────────────
    edu_amounts = np.zeros(n_new)
    has_dep = dep_new > 0
    if has_dep.any():
        pos_edu_mask = group["Dependents"] > 0
        edu_ratios = (
            group.loc[pos_edu_mask, "Education"]
            / group.loc[pos_edu_mask, "Income"]
        ).values
        er_logit = logit_transform(edu_ratios, *EDU_RATIO_BOUNDS)
        er_mu, er_std = er_logit.mean(), er_logit.std()
        sampled_er = sigmoid_inverse(
            np.random.normal(er_mu, er_std, has_dep.sum()), *EDU_RATIO_BOUNDS
        )
        edu_amounts[has_dep] = sampled_er * income_samples[has_dep]

    # ── Build expense absolute values from ratios × Income ───────────────────
    part = pd.DataFrame({
        "Income":      income_samples,
        "Age":         age_new,
        "Dependents":  dep_new,
        "Occupation":  occ,
        "City_Tier":   tier,
        **{col: ratio_samples[col] * income_samples for col in RATIO_COLS},
        "Loan_Repayment": loan_amounts,
        "Education":      edu_amounts,
        "Desired_Savings_Percentage": dsp_samples,
    })

    # ── Recompute derived columns (exact formulas) ───────────────────────────
    part["Disposable_Income"] = part["Income"] - part[EXPENSE_COLS].sum(axis=1)

    raw_savings = part["Income"] * part["Desired_Savings_Percentage"] / 100
    part["Desired_Savings"] = np.minimum(
        raw_savings, part["Disposable_Income"].clip(lower=0)
    )

    for col in ["Groceries", "Transport", "Eating_Out", "Entertainment", "Utilities", "Miscellaneous"]:
        part[f"Potential_Savings_{col}"] = np.random.uniform(0.05, 0.30, n_new) * part[col]

    for col in ["Healthcare", "Education"]:
        part[f"Potential_Savings_{col}"] = np.random.uniform(0.00, 0.05, n_new) * part[col]

    synthetic_parts.append(part)

synthetic_df = pd.concat(synthetic_parts, ignore_index=True)
synthetic_df = synthetic_df[df.columns.tolist()]

combined = pd.concat([df, synthetic_df], ignore_index=True)
combined.to_csv(OUTPUT_PATH, index=False)
print(f"\nDone. Total rows: {len(combined)}  →  {OUTPUT_PATH}")

# ── Validation ───────────────────────────────────────────────────────────────
print("\n── Column mean comparison (original vs synthetic) ──\n")
print(f"{'Column':<37} {'Original':>12} {'Synthetic':>12}  {'Δ%':>6}")
print("-" * 70)
for col in df.select_dtypes(include="number").columns:
    om = df[col].mean()
    sm = synthetic_df[col].mean()
    pct = abs(om - sm) / (abs(om) + 1e-9) * 100
    flag = " !" if pct > 10 else ""
    print(f"{col:<37} {om:>12.2f} {sm:>12.2f}  {pct:>5.1f}%{flag}")

neg_orig  = (df["Disposable_Income"] < 0).mean() * 100
neg_synth = (synthetic_df["Disposable_Income"] < 0).mean() * 100
print(f"\nNegative Disposable_Income: original={neg_orig:.1f}%  synthetic={neg_synth:.1f}%")

print("\nOccupation distribution:")
print(pd.concat({
    "original":  df["Occupation"].value_counts(normalize=True),
    "synthetic": synthetic_df["Occupation"].value_counts(normalize=True),
}, axis=1).round(3))

print("\nCity_Tier distribution:")
print(pd.concat({
    "original":  df["City_Tier"].value_counts(normalize=True),
    "synthetic": synthetic_df["City_Tier"].value_counts(normalize=True),
}, axis=1).round(3))
